### ISSUE TITLE
发生初始化错误

### ISSUE THREAD

**Issue by zhhdys258** [Hghhhh/gyro#1]
遇到一个问题，就是按gyro debugger的时候，出现如下错误

无法打开（C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14.plugins\jr-ide-idea\lib\jrebel6\lib\libjrebel64.dylib 不是有效的 Win32 应用程序。 ）
JVMJ9VM015W 在库 j9jvmti29(-3) 中发生初始化错误 JVMJ9VM009E J9VMDllMain 失败

**Comment by zhhdys258** [comment]
换成C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14.plugins\jr-ide-idea\lib\jrebel6\lib\jrebel64.dll后不报这个错了，不过启动挺慢。

**Comment by Hghhhh** [comment]
不好意思哈，Windows系统对Jrebel热部署的兼容没做好，Windows系统可以先到"Preferences->Tools->Gyro Settings"，把地址lib\后面改成："jrebel64.dll"即可，后续我升级版本兼容下

**Comment by Hghhhh** [comment]
> 换成C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14.plugins\jr-ide-idea\lib\jrebel6\lib\jrebel64.dll后不报这个错了，不过启动挺慢。

这个启动慢是第一次启动的时候，需要正常启动Spring容器，第二次再启动的时候，就会快很多了

**Comment by shadowyy** [comment]
谢谢作者，刚也遇到这个问题了，还是要做下系统兼容的
